version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install the requirements needed to build the documentation from the appropriate requirements.txt file
python:
  install:
    - requirements: doc-requirements.txt
