pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    ## We can enable different Python versions when
    ## there are unit tests.
    # Python36:
    #   python.version: '3.6'
    # Python38:
    #   python.version: '3.8'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pre-commit
  displayName: 'Install dependencies'

- script: |
    pre-commit install
    pre-commit run --all-files
  displayName: 'Run pre-commit on all files'
