site_name: AppDaemon
pages:
- Introduction: 'INTRO.md'
- Readme: 'README.md'
- Tutorial: 'TUTORIAL.md'
- API: 'API.md'
- HADashboard: 'DASHBOARD.md'
- Docker Tutorial: 'DOCKER_TUTORIAL.md'
- Changelog: 'HISTORY.md'
