site_name: AppDaemon
docs_dir: docs
theme: mkdocs
pages:
  - Introduction: 'index.md'
  - Installation: 'INSTALL.md'
  - Tutorial: 'TUTORIAL.md'
  - API Reference: 'API.md'
  - HADashboard: 'DASHBOARD.md'
  - Docker: 'DOCKER_TUTORIAL.md'
  - Changelog: 'HISTORY.md'
