#!/bin/bash
# Pushes a new version to PyPi.

cd "$(dirname "$0")/.."

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`

if [ "$CURRENT_BRANCH" != "master" ]
then
  echo "Warning: Current branch is $CURRENT_BRANCH - continue?"
  read -p "Warning: Current branch is $CURRENT_BRANCH - continue (y/n)? " -n 1 -r
  echo    # (optional) move to a new line
  if [[ ! $REPLY =~ ^[Yy]$ ]]
  then
    exit 1
  fi
fi

rm -rf build
rm -rf dist

python3 setup.py sdist bdist_wheel