name: Build Arm image

on:
  pull_request:
    branches: dev
  push:
    branches: dev
    paths-ignore:
    - '.github/**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: dev
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.0.1
        with:
          platforms: arm64,arm
      - name: Available QEMU platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1.1.1
        with: 
          version: latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Avaiable builx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build the image
        run: |
          docker buildx build --push \
            --tag "${{ secrets.DOCKERHUB_USERNAME }}"/appdaemon:dev \
            --platform linux/arm64,linux/arm/v7 .
