# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python lint and tests

on:
  push:
  pull_request:
    branches: ["dev"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install uv and set the python version
      id: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.15" # It is considered best practice to pin to a specific uv version
        # https://github.com/astral-sh/setup-uv?tab=readme-ov-file#enable-caching
        enable-cache: true
        cache-dependency-glob: |
          **/*requirements*.txt
          **/pyproject.toml
          **/uv.lock

    - name: Do something if the cache was restored
      if: steps.setup-uv.outputs.cache-hit == 'true'
      run: echo "Cache was restored"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run pre-commit hooks
      run: >
        uv run pre-commit
        run --all-files
        --show-diff-on-failure --color=always

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v5
    - name: Install uv and set the python version
      id: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        # https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
        python-version: ${{ matrix.python-version }}
        version: "0.8.15" # It is considered best practice to pin to a specific uv version
        # https://github.com/astral-sh/setup-uv?tab=readme-ov-file#enable-caching
        enable-cache: true
        cache-dependency-glob: |
          **/*requirements*.txt
          **/pyproject.toml
          **/uv.lock

    - name: Do something if the cache was restored
      if: steps.setup-uv.outputs.cache-hit == 'true'
      run: echo "Cache was restored"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      # For example, using `pytest`
      run: uv run pytest -m ci
